[Settings]
  ID = "districtbuilder"

[build]
  base = "."
  publish = "_site/"
  command = "jekyll build"

[context.production.environment]
  JEKYLL_ENV = "production"

[context.deploy-preview.environment]
  JEKYLL_ENV = "development"

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = """
      default-src 'self';
      connect-src 'self' https://www.google-analytics.com;
      script-src 'self' 'unsafe-inline' https://www.googletagmanager.com use.typekit.net https://www.google-analytics.com;
      style-src 'self' 'unsafe-inline' use.typekit.net p.typekit.net;
      img-src 'self' https://www.googletagmanager.com p.typekit.net https://www.google-analytics.com;
      font-src 'self' data://* use.typekit.net;
      """
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "no-referrer"
