[Settings]
  ID = "districtbuilder-marketing"

[build]
  base = "."
  publish = "_site/"
  command = "jekyll build"

[context.production.environment]
  JEKYLL_ENV = "production"

[context.deploy-preview.environment]
  JEKYLL_ENV = "development"

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = """
      default-src 'self';
      connect-src 'self' https://www.google-analytics.com https://ka-p.fontawesome.com;
      script-src 'self' 'unsafe-inline' https://www.googletagmanager.com https://tagmanager.google.com use.typekit.net https://www.google-analytics.com https://kit.fontawesome.com https://js.hs-scripts.com https://js.hs-scripts.net https://js.hs-banner.com https://js.hs-analytics.net https://cdn.jsdelivr.net/npm/intersection-observer@0.7.0/intersection-observer.js https://cdn.jsdelivr.net/npm/vanilla-lazyload@17.3.0/dist/lazyload.min.js;
      style-src 'self' 'unsafe-inline' use.typekit.net p.typekit.net https://kit-pro.fontawesome.com https://tagmanager.google.com https://fonts.googleapis.com;
      img-src 'self' https://www.googletagmanager.com p.typekit.net https://www.google-analytics.com https://ssl.gstatic.com https://www.gstatic.com https://track.hubspot.com;
      font-src 'self' data: use.typekit.net https://ka-p.fontawesome.com https://kit-pro.fontawesome.com https://fonts.gstatic.com;
      """
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "no-referrer"
